#YAML
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: webthing-iotjs
spec:
  replicas: 1
  template:
    metadata:
      labels:
        run: webthing-iotjs
    spec:
      containers:
      - image: rzrfreefr/webthing-iotjs:latest
        name: webthing-iotjs
        ports:
        - containerPort: 8888
---
apiVersion: v1
kind: Service
metadata:
  name: webthing-iotjs
spec:
  ports:
  - nodePort: 30080
    port: 8888
    protocol: TCP
    targetPort: 8888
  selector:
    run: webthing-iotjs
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
---
